-- MySQL Script generated by MySQL Workbench
-- Mon Jun 17 13:05:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`contactos_paci_emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contactos_paci_emergencia` (
  `id_cpe` VARCHAR(11) NOT NULL,
  `id_paci` VARCHAR(45) NULL,
  `nombrecompleto_cpe` VARCHAR(45) NULL,
  `relacion_cpe` ENUM("Familiar", "Amigo") NULL,
  `numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cpe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`planes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planes` (
  `id_plan` VARCHAR(11) NOT NULL,
  `descripcion_plan` VARCHAR(45) NULL,
  `dto_consultas` VARCHAR(45) NULL,
  `dto_medicamentos` VARCHAR(45) NULL,
  PRIMARY KEY (`id_plan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pacientes` (
  `id_paci` VARCHAR(11) NOT NULL,
  `credencial_paci` VARCHAR(45) NOT NULL,
  `apellido_paci` VARCHAR(45) NOT NULL,
  `nombre_paci` VARCHAR(45) NULL,
  `nacimiento_paci` VARCHAR(45) NULL,
  `provincia_dom_paci` VARCHAR(45) NULL,
  `localidad_dom_paci` VARCHAR(45) NULL,
  `calle_dom_paci` VARCHAR(45) NULL,
  `num_dom_paci` VARCHAR(45) NULL,
  `numero_emer_paci` VARCHAR(45) NULL,
  `correo_paci` VARCHAR(45) NULL,
  `id_contactoemergencia` VARCHAR(11) NULL,
  `id_plan` VARCHAR(11) NULL,
  PRIMARY KEY (`id_paci`),
  INDEX `FK_cpe_idx` (`id_contactoemergencia` ASC) VISIBLE,
  INDEX `FK_plan_idx` (`id_plan` ASC) VISIBLE,
  CONSTRAINT `FK_cpe`
    FOREIGN KEY (`id_contactoemergencia`)
    REFERENCES `mydb`.`contactos_paci_emergencia` (`id_cpe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_plan`
    FOREIGN KEY (`id_plan`)
    REFERENCES `mydb`.`planes` (`id_plan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medicos` (
  `id_medi` VARCHAR(11) NOT NULL,
  `legajo_medi` VARCHAR(45) NOT NULL,
  `nombre_med` VARCHAR(45) NULL,
  `apellido_med` VARCHAR(45) NULL,
  `nacimiento_med` VARCHAR(45) NULL,
  `ingreso_med` DATE NOT NULL,
  `egreso_med` DATE NULL,
  PRIMARY KEY (`id_medi`),
  UNIQUE INDEX `legajo_medi_UNIQUE` (`legajo_medi` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias_especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias_especialidades` (
  `id_esca` VARCHAR(11) NOT NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_esca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especialidades` (
  `id_espe` VARCHAR(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `especialidades_categorias_id_esca` INT NOT NULL,
  PRIMARY KEY (`id_espe`),
  INDEX `fk_especialidades_especialidades_categorias1_idx` (`especialidades_categorias_id_esca` ASC) VISIBLE,
  CONSTRAINT `fk_especialidades_especialidades_categorias1`
    FOREIGN KEY (`especialidades_categorias_id_esca`)
    REFERENCES `mydb`.`categorias_especialidades` (`id_esca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medicos_especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medicos_especialidad` (
  `id_meep` VARCHAR(11) NOT NULL,
  `id_medico` VARCHAR(11) NOT NULL,
  `id_especialidad` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_meep`),
  INDEX `FK_medicos_especialidad_idx` (`id_especialidad` ASC) VISIBLE,
  INDEX `FK_medico_idx` (`id_medico` ASC) VISIBLE,
  CONSTRAINT `FK_especialidad`
    FOREIGN KEY (`id_especialidad`)
    REFERENCES `mydb`.`especialidades` (`id_espe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_medico`
    FOREIGN KEY (`id_medico`)
    REFERENCES `mydb`.`medicos` (`id_medi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disponibilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disponibilidades` (
  `id_disp` VARCHAR(11) NOT NULL,
  `horainicio_disp` TIME NOT NULL,
  `horafin_disp` TIME NULL,
  `id_meep` VARCHAR(11) NULL,
  `dia_disp` ENUM("Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo") NULL,
  PRIMARY KEY (`id_disp`),
  INDEX `FK_meep_idx` (`id_meep` ASC) VISIBLE,
  CONSTRAINT `FK_meep`
    FOREIGN KEY (`id_meep`)
    REFERENCES `mydb`.`medicos_especialidad` (`id_meep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`citas` (
  `id_cita` VARCHAR(11) NOT NULL,
  `id_disp` VARCHAR(11) NOT NULL,
  `id_paci` VARCHAR(11) NOT NULL,
  `horario_cita` TIME NOT NULL,
  `asistio_cita` TINYINT NOT NULL,
  PRIMARY KEY (`id_cita`),
  INDEX `FK_disp_idx` (`id_disp` ASC) VISIBLE,
  INDEX `FK_paci_idx` (`id_paci` ASC) VISIBLE,
  CONSTRAINT `FK_disp`
    FOREIGN KEY (`id_disp`)
    REFERENCES `mydb`.`disponibilidades` (`id_disp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_paci`
    FOREIGN KEY (`id_paci`)
    REFERENCES `mydb`.`pacientes` (`id_paci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `pacientes_id_paci` VARCHAR(11) NOT NULL,
  `user_usua` VARCHAR(45) NOT NULL,
  `password_usua` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pacientes_id_paci`),
  UNIQUE INDEX `user_usua_UNIQUE` (`user_usua` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_pacientes`
    FOREIGN KEY (`pacientes_id_paci`)
    REFERENCES `mydb`.`pacientes` (`id_paci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`VIEW_citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIEW_citas` (`id_paci` INT, `horario_cita` INT, `nombre_med` INT, `apellido_med` INT, `descripcion` INT, `asistio_cita` INT);

-- -----------------------------------------------------
-- procedure GetCitasByPaciente
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE `GetCitasByPaciente` (IN id_paciente INT)
BEGIN
	SELECT * FROM VIEW_citas WHERE id_paci = id_paciente;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `mydb`.`VIEW_citas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VIEW_citas`;
USE `mydb`;
CREATE  OR REPLACE VIEW `VIEW_citas` AS
    SELECT 
        citas.id_paci,
        citas.horario_cita,
        medicos.nombre_med,
        medicos.apellido_med,
        espe.descripcion,
        citas.asistio_cita
    FROM
        citas
            INNER JOIN
        disponibilidades AS disp ON citas.id_disp = disp.id_disp
            INNER JOIN
        medicos_especialidad AS meep ON disp.id_meep = meep.id_meep
            INNER JOIN
        medicos ON meep.id_medico = medicos.id_medi
            INNER JOIN
        especialidades AS espe ON meep.id_especialidad = espe.id_espe;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
